// dlopen.go — generate the compiled-in plugin table for --wrap-dlopen.
//
// Spec: NAME=OBJECT[,OBJECT...]. NAME is what the program passes to dlopen();
// OBJECT is any .o or .a the build produced, and its defined external symbols
// become that plugin's dlsym table.
//
// Every symbol a plugin defines is renamed to a per-plugin prefix with
// `objcopy --redefine-syms`, and the table maps the original name to the
// renamed one. That reproduces the private namespace a real loader gives each
// object: without it, two plugins defining the same symbol — which every
// SQLite extension does, and which upstreams do deliberately for entry points
// derived from a filename — collide at link time. Only defined symbols are
// renamed, so a plugin's calls back into the host program still bind.
//
// SPDX-License-Identifier: MIT
package wrapper

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/polaris0xff/glibc-research/internal/elfx"
	"github.com/polaris0xff/glibc-research/internal/fail"
	"github.com/polaris0xff/glibc-research/internal/proc"
)

// PluginSpec is one parsed --wrap-dlopen argument.
type PluginSpec struct {
	Name    string
	Objects []string
}

// ParsePluginSpec splits NAME=OBJECT[,OBJECT...].
func ParsePluginSpec(spec string) (PluginSpec, error) {
	name, objs, ok := strings.Cut(spec, "=")
	if !ok || name == "" || objs == "" {
		return PluginSpec{}, fail.Cannot("--wrap-dlopen wants NAME=OBJECT[,OBJECT...], got: %s", spec)
	}
	var list []string
	for _, o := range strings.Split(objs, ",") {
		if o = strings.TrimSpace(o); o != "" {
			list = append(list, o)
		}
	}
	if len(list) == 0 {
		return PluginSpec{}, fail.Cannot("--wrap-dlopen: %s names no objects", name)
	}
	return PluginSpec{Name: name, Objects: list}, nil
}

func (b *Builder) buildDlopenTable(rd, src string) error {
	if !proc.Look("objcopy") {
		return fail.Cannot("--wrap-dlopen needs objcopy (binutils) to namespace plugin symbols")
	}

	var gen bytes.Buffer
	gen.WriteString("/* generated by pgb: rebuilt on every build */\n")
	fmt.Fprintf(&gen, "#include \"%s/pgb-dlopen.h\"\n\n", src)

	var linkObjects []string
	var tableRows []string

	for idx, raw := range b.C.WrapDlopen {
		spec, err := ParsePluginSpec(raw)
		if err != nil {
			return err
		}
		var syms []string
		for _, o := range spec.Objects {
			if !exists(o) {
				return fail.Cannot("--wrap-dlopen: no such object: %s", o)
			}
			s, err := elfx.DefinedExternalSymbols(o)
			if err != nil {
				return fail.Cannot("--wrap-dlopen: cannot read %s: %v", o, err)
			}
			syms = append(syms, s...)
		}
		syms = uniqueSorted(syms)
		if len(syms) == 0 {
			return fail.Ran("--wrap-dlopen: %s has no defined external symbols in: %s",
				spec.Name, strings.Join(spec.Objects, " "))
		}

		prefix := fmt.Sprintf("pgb_dl%d_", idx)
		mapFile := filepath.Join(rd, fmt.Sprintf("pgb-dlopen-renames-%d.txt", idx))
		var renames bytes.Buffer
		for _, s := range syms {
			fmt.Fprintf(&renames, "%s %s%s\n", s, prefix, s)
		}
		if err := os.WriteFile(mapFile, renames.Bytes(), 0o644); err != nil {
			return err
		}
		for ni, o := range spec.Objects {
			out := filepath.Join(rd, fmt.Sprintf("pgb-dl-%d-%d-%s", idx, ni, filepath.Base(o)))
			r, err := (&proc.Cmd{
				Argv:   []string{"objcopy", "--redefine-syms=" + mapFile, o, out},
				Subsys: "wrapper",
			}).Output()
			if err != nil || r.Failed() {
				return fail.Ran("--wrap-dlopen: could not namespace %s: %s", o,
					strings.TrimSpace(string(r.Stderr)))
			}
			// The namespaced copy goes on the link line, never the original:
			// linking both reintroduces the collision the renaming removes.
			linkObjects = append(linkObjects, out)
		}

		for _, s := range syms {
			fmt.Fprintf(&gen, "extern char %s%s[];\n", prefix, s)
		}
		fmt.Fprintf(&gen, "\nstatic const struct pgb_dl_sym pgb_dl_syms_%d[] = {\n", idx)
		for _, s := range syms {
			fmt.Fprintf(&gen, "    { \"%s\", (void *)%s%s },\n", s, prefix, s)
		}
		gen.WriteString("    { NULL, NULL }\n};\n\n")
		tableRows = append(tableRows, fmt.Sprintf("    { \"%s\", pgb_dl_syms_%d },", spec.Name, idx))
	}

	gen.WriteString("const struct pgb_dl_lib pgb_dlopen_libs[] = {\n")
	for _, row := range tableRows {
		gen.WriteString(row + "\n")
	}
	gen.WriteString("    { NULL, NULL }\n};\n")

	genPath := filepath.Join(rd, "pgb-dlopen-table.c")
	if err := os.WriteFile(genPath, gen.Bytes(), 0o644); err != nil {
		return err
	}
	log.Infof("generated %s (%d plugin(s))", genPath, len(tableRows))
	if err := b.compile(genPath, filepath.Join(rd, "pgb-dlopen-table.o"), "-O2"); err != nil {
		return err
	}
	if err := b.compileIfStale(src, "pgb-dlopen.c", filepath.Join(rd, "pgb-dlopen.o"), "-O2"); err != nil {
		return err
	}
	// The plugin objects must be on the link line: the table takes their
	// addresses, and an object nobody references is not pulled from an archive.
	return os.WriteFile(filepath.Join(rd, "pgb-dlopen-objs"),
		[]byte(strings.Join(linkObjects, "\n")+"\n"), 0o644)
}

// dlopenObjects reads back the namespaced plugin objects recorded above.
func dlopenObjects(rd string) []string {
	b, err := os.ReadFile(filepath.Join(rd, "pgb-dlopen-objs"))
	if err != nil {
		return nil
	}
	return strings.Fields(string(b))
}

func uniqueSorted(in []string) []string {
	seen := make(map[string]bool, len(in))
	out := make([]string, 0, len(in))
	for _, s := range in {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	sortStrings(out)
	return out
}
