// hostdlopen.go — generate the provider table the compiled-in ELF loader
// resolves a HOST shared object against.
//
// This is dlopen.go's mechanism pointed one layer up. --wrap-dlopen builds a
// table of the application's OWN plugins and answers dlopen out of it without
// mapping anything. --host-dlopen builds a table of THIS EXECUTABLE'S STATIC
// GLIBC and hands it to tool/runtime/pgb-elfload.c, which does map the object,
// relocates it, and binds its undefined symbols to that table. A DT_NEEDED
// naming a soname the table already serves is answered rather than opened,
// which is what keeps the host's libc.so.6 and ld.so out of the process.
//
// ⭐ THE WEAK REFERENCE IS THE MECHANISM. Every row is
//
//	extern char NAME[] __attribute__((weak));
//
// so listing a name costs its string and a pointer and does NOT pull the
// archive member that defines it. What decides how much of libc.a is linked is
// the SEPARATE -u list emitted beside the table. Measured on the host spike:
//
//	table only, no -u   946,752 bytes   1,251 of 4,891 names had addresses
//	                                    and the first load failed on
//	                                    __errno_location
//	full -u list      2,621,872 bytes   4,891 of 4,891, and the load worked
//
// so the cost of a complete table is about 1.6 MB and it is a dial, not a
// constant.
//
// SPDX-License-Identifier: MIT
package wrapper

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/polaris0xff/glibc-research/internal/elfx"
	"github.com/polaris0xff/glibc-research/internal/fail"
)

// providerArchives are the static libraries whose symbols a loaded host object
// may bind to. libm.a is a GNU ld script on Debian and Ubuntu and is expanded
// by elfx.ExpandLinkerScripts; a name that does not exist on this glibc is
// skipped rather than failing, because the set differs between distributions.
var providerArchives = []string{
	"libc.a", "libm.a", "libpthread.a", "libdl.a", "librt.a",
	"libutil.a", "libresolv.a", "libcrypt.a", "libanl.a", "libmvec.a",
}

// providerSonames are answered out of the table instead of being mapped.
//
// ⛔ EVERY NAME HERE IS A LIBRARY THIS IMAGE ALREADY CONTAINS. Mapping any of
// them would put a second libc in the process, which is the exact outcome
// docs/limitations.md §1 calls worse than failing.
var providerSonames = []string{
	"libc.so.6", "libm.so.6", "libpthread.so.0", "libdl.so.2",
	"librt.so.1", "libutil.so.1", "libresolv.so.2", "libcrypt.so.1",
	"libanl.so.1", "libBrokenLocale.so.1", "ld-linux-x86-64.so.2",
}

// libSearchDirs is where the pinned build environment keeps its static glibc.
var libSearchDirs = []string{
	"/usr/lib/x86_64-linux-gnu", "/usr/lib64", "/usr/lib", "/lib64", "/lib",
}

func (b *Builder) buildProviderTable(rd, src string) error {
	var paths []string
	for _, dir := range libSearchDirs {
		for _, a := range providerArchives {
			p := filepath.Join(dir, a)
			if _, err := os.Stat(p); err == nil {
				paths = append(paths, p)
			}
		}
	}
	if len(paths) == 0 {
		return fail.Cannot("--host-dlopen found no static glibc archives in %s",
			strings.Join(libSearchDirs, ", "))
	}

	syms, err := elfx.ReadProviderSymbols(paths)
	if err != nil {
		return fail.Ran("--host-dlopen: cannot read the static glibc: %v", err)
	}
	if len(syms.Defined) == 0 {
		return fail.Ran("--host-dlopen: the static glibc archives defined no "+
			"symbols; read %d file(s)", len(paths))
	}

	var gen bytes.Buffer
	gen.WriteString("/* generated by pgb: rebuilt on every build */\n")
	fmt.Fprintf(&gen, "#include \"%s/pgb-elfload.h\"\n\n", src)
	fmt.Fprintf(&gen, "/* %d providers from %d archive(s); %d thread-local "+
		"symbols excluded */\n", len(syms.Defined), len(paths), len(syms.TLS))
	for _, s := range syms.Defined {
		fmt.Fprintf(&gen, "extern char %s[] __attribute__((weak));\n", s)
	}
	gen.WriteString("\nconst struct pgb_provider_sym pgb_provider_syms[] = {\n")
	for _, s := range syms.Defined {
		fmt.Fprintf(&gen, "    { \"%s\", %s },\n", s, s)
	}
	gen.WriteString("    { NULL, NULL }\n};\n\n")
	gen.WriteString("const char *const pgb_provider_sonames[] = {\n")
	for _, s := range providerSonames {
		fmt.Fprintf(&gen, "    \"%s\",\n", s)
	}
	gen.WriteString("    NULL\n};\n")

	genPath := filepath.Join(rd, "pgb-provider-table.c")
	if err := os.WriteFile(genPath, gen.Bytes(), 0o644); err != nil {
		return err
	}

	// The -u list, as a linker response file. One flag per line: 7,000 of them
	// do not fit on a command line, and @file is how ld takes them.
	var u bytes.Buffer
	for _, s := range syms.Defined {
		fmt.Fprintf(&u, "-u %s\n", s)
	}
	if err := os.WriteFile(filepath.Join(rd, "pgb-provider-u.rsp"), u.Bytes(), 0o644); err != nil {
		return err
	}

	log.Infof("generated %s (%d providers, %d TLS excluded)", genPath,
		len(syms.Defined), len(syms.TLS))

	// ⚠ -fno-builtin, because a weak `extern char memcpy[]` collides with the
	// compiler's own declaration of the builtin otherwise. The table takes
	// addresses and calls nothing, so nothing is lost by turning them off.
	if err := b.compile(genPath, filepath.Join(rd, "pgb-provider-table.o"),
		"-O2", "-fno-builtin", "-w"); err != nil {
		return err
	}
	// ⛔ THE RESERVE SIZE IS IN THE OBJECT'S NAME, and it has to be.
	// compileIfStale compares mtimes and nothing else -- it does not know what
	// flags produced the object -- and Dir() is keyed on the compiler's
	// identity plus the asset digest, not on the build options. So two builds
	// differing only in --tls-reserve would share one pgb-elfload.o and the
	// second would silently get the first's reserve. That is the artefact-cache
	// defect this tree has already paid for once; a distinct path per size
	// makes the mtime rule correct instead of working around it.
	if err := b.compileIfStale(src, "pgb-elfload.c", elfloadObj(rd, b.C.TLSReserve),
		"-O2", fmt.Sprintf("-DPGB_TLS_RESERVE=%d", b.C.TLSReserve)); err != nil {
		return err
	}
	// pgb-dlopen.o carries the --wrap entry points and falls through to the
	// loader. --wrap-dlopen compiles it too, but --host-dlopen can be asked
	// for on its own and the link names the object either way.
	return b.compileIfStale(src, "pgb-dlopen.c",
		filepath.Join(rd, "pgb-dlopen.o"), "-O2")
}

// hostDlopenLinkFlags are the link-line pieces --host-dlopen adds.
//
// ⛔ THE ARCHIVE GROUP IS NOT OPTIONAL. The -u list names symbols spread over
// libresolv.a, libanl.a and the rest, and a single-pass linker resolves each
// archive where it appears. Without --start-group the first full table failed
// the link on 40-odd sunrpc and resolver names.
// elfloadObj is where the loader object for one reserve size lives. The size is
// part of the name so the mtime-based staleness check cannot serve an object
// built for a different reserve.
func elfloadObj(rd string, reserve int) string {
	if reserve == 0 {
		return filepath.Join(rd, "pgb-elfload.o")
	}
	return filepath.Join(rd, fmt.Sprintf("pgb-elfload-tls%d.o", reserve))
}

func hostDlopenLinkFlags(rd string, reserve int) []string {
	if _, err := os.Stat(filepath.Join(rd, "pgb-provider-table.o")); err != nil {
		return nil
	}
	return []string{
		elfloadObj(rd, reserve),
		filepath.Join(rd, "pgb-provider-table.o"),
		"-Wl,@" + filepath.Join(rd, "pgb-provider-u.rsp"),
		"-Wl,--start-group",
		"-lm", "-lpthread", "-ldl", "-lrt", "-lutil", "-lresolv", "-lcrypt", "-lanl",
		"-Wl,--end-group",
	}
}
