// sharun.go — sharun as AppRun, the hardlinks it dispatches on, and the
// environment the bundle carries.
//
// The hardlink is the mechanism, not a shortcut: sharun looks at the name it
// was invoked as and runs shared/bin/<that name>, which is how /proc/self/exe
// ends up naming the application rather than the loader. The hardlinks go at
// the TOP level, because sharun takes its AppDir from its own location — one
// under bin/ makes it treat bin/ as the root, where there is no .env and no
// lib, and a Qt application then aborts with no output at all.
//
// SPDX-License-Identifier: MIT
package bundle

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/polaris0xff/glibc-research/internal/elfx"
	"github.com/polaris0xff/glibc-research/internal/fail"
	"github.com/polaris0xff/glibc-research/internal/logx"
	"github.com/polaris0xff/glibc-research/internal/nixx"
	"github.com/polaris0xff/glibc-research/internal/proc"
)

func (b *Builder) installSharun() error {
	tools := filepath.Join(b.O.Cache, "tools")
	sharun := filepath.Join(tools, "sharun")
	if err := download(envOr("SHARUN_URL", toolURL(defaultSharunURL, b.Arch)), sharun); err != nil {
		return fail.Ran("could not fetch sharun: %v", err)
	}
	appSharun := filepath.Join(b.AppDir, "sharun")
	if err := copyResolved(sharun, appSharun, 0o755); err != nil {
		return err
	}

	entries, err := os.ReadDir(filepath.Join(b.AppDir, "shared", "bin"))
	if err != nil {
		return err
	}
	programs := 0
	for _, e := range entries {
		if e.IsDir() || reservedNames[e.Name()] {
			continue
		}
		programs++
		for _, at := range []string{
			filepath.Join(b.AppDir, e.Name()),
			filepath.Join(b.AppDir, "bin", e.Name()),
		} {
			_ = os.Remove(at)
			if err := os.Link(appSharun, at); err != nil {
				_ = copyResolved(appSharun, at, 0o755)
			}
		}
	}

	appRun := filepath.Join(b.AppDir, "AppRun")
	_ = os.Remove(appRun)
	switch {
	case programs <= 1:
		// A single-program bundle pays nothing: AppRun is sharun itself.
		if err := os.Link(appSharun, appRun); err != nil {
			if err := copyResolved(appSharun, appRun, 0o755); err != nil {
				return err
			}
		}
		logx.Say("apprun      sharun itself (one program: no shell, no host interpreter)")
	default:
		// A static selector, not a shell script. A script is run by the HOST's
		// interpreter, which loads the HOST's libc — measured as 1-4 host
		// shared objects on every glibc row.
		if err := b.buildStaticAppRun(appRun); err != nil {
			logx.Warnf("no static AppRun could be built (%v), so it falls back to a SHELL", err)
			logx.Warnf("   SCRIPT selector -- which loads the HOST's /bin/sh and its libc.")
			if err := b.writeShellAppRun(appRun); err != nil {
				return err
			}
		} else {
			fi, _ := os.Stat(appRun)
			logx.Say("apprun      pgb-apprun, static, %d bytes (no host interpreter)", fi.Size())
		}
	}

	if r, err := (&proc.Cmd{Argv: []string{"./sharun", "--gen-lib-path"}, Dir: b.AppDir,
		Subsys: "bundle"}).Output(); err != nil || r.Failed() {
		logx.Warnf("sharun --gen-lib-path failed")
	}
	if fi, err := os.Stat(filepath.Join(b.AppDir, "lib", "lib.path")); err == nil && fi.Size() > 0 {
		data, _ := os.ReadFile(filepath.Join(b.AppDir, "lib", "lib.path"))
		logx.Say("lib.path    %d entries", strings.Count(string(data), "\n"))
	}
	return nil
}

// buildStaticAppRun compiles the carried selector. The readelf-equivalent
// check is not decoration: a cc that quietly produced a dynamic binary would
// put the host's loader back in the bundle.
func (b *Builder) buildStaticAppRun(out string) error {
	src, err := materialiseAppRunSource(b.C.RuntimeSrcDir())
	if err != nil {
		return err
	}
	r, err := (&proc.Cmd{Argv: []string{"cc", "-O2", "-static",
		"-DPGB_APPRUN_DEFAULT=\"" + b.Prog + "\"", "-o", out, src},
		Subsys: "bundle"}).Output()
	if err != nil {
		return err
	}
	if r.Failed() {
		return fmt.Errorf("cc exited %d", r.Code)
	}
	info, err := elfx.Inspect(out)
	if err != nil {
		return err
	}
	if info.Interp != "" {
		_ = os.Remove(out)
		return fmt.Errorf("the compiler produced a DYNAMIC AppRun")
	}
	return nil
}

func (b *Builder) writeShellAppRun(out string) error {
	body := fmt.Sprintf(`#!/bin/sh
# generated by pgb bundle appimage -- the selector
APPDIR="${APPDIR:-$(dirname "$(readlink -f "$0")")}"
ARG0="${ARGV0:-$0}"; unset ARGV0
export APPDIR
if [ -f "$APPDIR/${ARG0##*/}" ] && [ -f "$APPDIR/shared/bin/${ARG0##*/}" ]; then
  exec "$APPDIR/${ARG0##*/}" "$@"
elif [ -n "$1" ] && [ -f "$APPDIR/shared/bin/$1" ]; then
  _p="$1"; shift; exec "$APPDIR/$_p" "$@"
else
  exec "$APPDIR/%s" "$@"
fi
`, b.Prog)
	return os.WriteFile(out, []byte(body), 0o755)
}

// bakedOverride is the variable that redirects a program to a directory it had
// compiled in. The directories are found rather than assumed; the variable
// cannot be derived, so this is a small table, each row naming the project it
// serves, and anything not in it is reported rather than silently left broken.
func bakedOverride(storeName, sub string) []string {
	switch {
	case strings.HasPrefix(sub, "lib/mlt-"):
		return []string{fmt.Sprintf("MLT_REPOSITORY=${SHARUN_DIR}/store/%s/%s", storeName, sub)}
	case strings.HasPrefix(sub, "share/mlt-"):
		return []string{
			fmt.Sprintf("MLT_DATA=${SHARUN_DIR}/store/%s/%s", storeName, sub),
			fmt.Sprintf("MLT_PROFILES_PATH=${SHARUN_DIR}/store/%s/%s/profiles", storeName, sub),
			fmt.Sprintf("MLT_PRESETS_PATH=${SHARUN_DIR}/store/%s/%s/presets", storeName, sub),
		}
	case strings.HasPrefix(sub, "lib/frei0r-"):
		return []string{fmt.Sprintf("FREI0R_PATH=${SHARUN_DIR}/store/%s/%s", storeName, sub)}
	case strings.HasPrefix(sub, "lib/ladspa"):
		return []string{fmt.Sprintf("LADSPA_PATH=${SHARUN_DIR}/store/%s/%s", storeName, sub)}
	case strings.HasPrefix(sub, "lib/gstreamer-"):
		return []string{fmt.Sprintf("GST_PLUGIN_SYSTEM_PATH_1_0=${SHARUN_DIR}/store/%s/%s", storeName, sub)}
	case strings.HasPrefix(sub, "lib/babl-"):
		return []string{fmt.Sprintf("BABL_PATH=${SHARUN_DIR}/store/%s/%s", storeName, sub)}
	case strings.HasPrefix(sub, "lib/gegl-"):
		return []string{fmt.Sprintf("GEGL_PATH=${SHARUN_DIR}/store/%s/%s", storeName, sub)}
	}
	return nil
}

var storeRefWithSub = regexp.MustCompile(`/nix/store/[a-z0-9]{32}-[A-Za-z0-9._+-]+/[A-Za-z0-9._+/-]*`)

// writeEnv writes .env: the paths sharun needs, the environment lifted out of
// a nixpkgs wrapper, and the overrides for directories a program had compiled
// in. Every path is set only if the bundle actually has it.
func (b *Builder) writeEnv() error {
	var lines []string
	add := func(format string, a ...any) { lines = append(lines, fmt.Sprintf(format, a...)) }
	have := func(rel string) bool {
		_, err := os.Stat(filepath.Join(b.AppDir, rel))
		return err == nil
	}

	add("XDG_DATA_DIRS=${SHARUN_DIR}/share:${XDG_DATA_DIRS}:/usr/local/share:/usr/share")
	add("GCONV_PATH=${SHARUN_DIR}/lib/gconv")
	add("FONTCONFIG_PATH=${SHARUN_DIR}/share/fontconfig/conf.d")
	if have("lib/gtk-3.0") {
		add("GTK_PATH=${SHARUN_DIR}/lib/gtk-3.0")
	}
	if have("lib/gdk-pixbuf-2.0/2.10.0/loaders.cache") {
		add("GDK_PIXBUF_MODULE_FILE=${SHARUN_DIR}/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache")
	}
	if have("lib/gbm") {
		add("GBM_BACKENDS_PATH=${SHARUN_DIR}/lib/gbm")
	}

	// ⭐ THE DRIVER AND FALLBACK CLASSES ARE THE POLICY'S, NOT THIS FUNCTION'S.
	// Bundled-first with a documented lowest-priority host fallback and
	// per-class opt-ins: docs/design/host-fallback.md, TODO T-065. Before this
	// the bundle set only its own paths and could never reach the host's
	// NVIDIA driver, which is the one thing it must never bundle.
	list := func(rel string) []string {
		entries, err := os.ReadDir(filepath.Join(b.AppDir, rel))
		if err != nil {
			return nil
		}
		var out []string
		for _, e := range entries {
			if !e.IsDir() {
				out = append(out, e.Name())
			}
		}
		return out
	}
	lines = append(lines, b.Host.EnvLines(have, list)...)

	lines = append(lines, b.liftWrapperEnv()...)
	lines = append(lines, b.carryBakedPaths()...)

	envPath := filepath.Join(b.AppDir, ".env")
	if err := os.WriteFile(envPath, []byte(strings.Join(lines, "\n")+"\n"), 0o644); err != nil {
		return err
	}
	keys, before, after, err := FoldEnv(envPath)
	if err == nil && keys > 0 {
		logx.Say("env         %d -> %d bytes after folding (%d keys)", before, after, keys)
	}
	return nil
}

// liftWrapperEnv turns the records read out of a nixpkgs wrapper into .env
// lines with the same semantics, copying the directory each value names.
//
// The SUBDIRECTORY the variable names is copied, not the whole package: a
// value like QT_PLUGIN_PATH names one directory, and copying the entire store
// path for it duplicates shared objects the bundle has already flattened into
// its own lib/.
func (b *Builder) liftWrapperEnv() []string {
	if len(b.wrapEnv) == 0 {
		return nil
	}
	storeDir := filepath.Join(b.AppDir, "store")
	if err := os.MkdirAll(storeDir, 0o755); err != nil {
		return nil
	}
	refs := map[string]bool{}
	for _, r := range b.wrapEnv {
		for _, m := range storeRefWithSub.FindAllString(r.Value, -1) {
			refs[m] = true
		}
		for _, m := range regexp.MustCompile(`/nix/store/[a-z0-9]{32}-[^:; ]*`).FindAllString(r.Value, -1) {
			refs[m] = true
		}
	}
	var sorted []string
	for r := range refs {
		sorted = append(sorted, r)
	}
	sortStrings(sorted)
	for _, ref := range sorted {
		rest := strings.TrimPrefix(ref, "/nix/store/")
		base, sub, _ := strings.Cut(rest, "/")
		short := base
		if len(short) > 33 {
			short = short[33:]
		}
		if _, err := os.Stat(filepath.Join(b.Root, base)); err != nil {
			if _, ferr := b.Nix.Fetch("/nix/store/"+base, nixx.FetchOptions{Out: b.Root, WithClosure: true}); ferr != nil {
				logx.Warnf("wrapper env names %s, which is not in the closure and could not be fetched", base)
				continue
			}
		}
		if sub != "" {
			src := filepath.Join(b.Root, base, sub)
			if _, err := os.Stat(src); err == nil {
				dst := filepath.Join(storeDir, short, sub)
				if _, err := os.Stat(dst); err != nil {
					_ = os.MkdirAll(filepath.Dir(dst), 0o755)
					_ = copyTreeNoClobber(src, dst)
				}
				continue
			}
		}
		dst := filepath.Join(storeDir, short)
		if _, err := os.Stat(dst); err != nil {
			_ = copyTreeNoClobber(filepath.Join(b.Root, base), dst)
		}
	}

	rewrite := regexp.MustCompile(`/nix/store/[a-z0-9]{32}-([^/:; ]*)`)
	var out []string
	for _, r := range b.wrapEnv {
		if r.Var == "" {
			continue
		}
		v := rewrite.ReplaceAllString(r.Value, "${SHARUN_DIR}/store/$1")
		sep := r.Sep
		if sep == "" {
			sep = ":"
		}
		switch r.Op {
		case OpSet:
			out = append(out, fmt.Sprintf("%s=%s", r.Var, v))
		case OpPrefix:
			out = append(out, fmt.Sprintf("%s=%s%s${%s}", r.Var, v, sep, r.Var))
		case OpSuffix:
			out = append(out, fmt.Sprintf("%s=${%s}%s%s", r.Var, r.Var, sep, v))
		}
	}
	if len(out) > 0 {
		logx.Say("wrapper env %d variable(s) lifted out of the wrapper into .env", len(out))
	}
	return out
}

// carryBakedPaths finds directories a program had compiled in and carries the
// ones an override can redirect.
//
// A wrapper is not the only way a program learns where its plugins are: MLT
// bakes its module directory into libmlt at build time and nixpkgs does not
// wrap it, so a bundle can pass every other check and still not render.
//
// Detection is cheap; carrying is not. Everything is found and counted, and
// only a directory the override table can redirect is carried — the rest are
// lib/ trees whose objects are already flattened into the bundle's own lib/.
func (b *Builder) carryBakedPaths() []string {
	logx.Say("scanning the packed binaries for compiled-in store paths")
	files := []string{}
	if entries, err := os.ReadDir(filepath.Join(b.AppDir, "shared", "bin")); err == nil {
		for _, e := range entries {
			files = append(files, filepath.Join(b.AppDir, "shared", "bin", e.Name()))
		}
	}
	if entries, err := os.ReadDir(filepath.Join(b.AppDir, "lib")); err == nil {
		for _, e := range entries {
			if !e.IsDir() && strings.HasPrefix(e.Name(), "lib") && IsSharedObject(e.Name()) {
				files = append(files, filepath.Join(b.AppDir, "lib", e.Name()))
			}
		}
	}

	seen := map[string]bool{}
	var refs []string
	for _, f := range files {
		data, err := os.ReadFile(f)
		if err != nil {
			continue
		}
		for _, m := range storeRefWithSub.FindAllString(string(data), -1) {
			if !seen[m] {
				seen[m] = true
				refs = append(refs, m)
			}
		}
	}
	sortStrings(refs)

	var out []string
	var vars []string
	nDir, nCarried := 0, 0
	for _, ref := range refs {
		rest := strings.TrimPrefix(ref, "/nix/store/")
		base, sub, ok := strings.Cut(rest, "/")
		if !ok || sub == "" {
			continue
		}
		src := filepath.Join(b.Root, base, sub)
		if fi, err := os.Stat(src); err != nil || !fi.IsDir() {
			continue
		}
		nDir++
		short := base
		if len(short) > 33 {
			short = short[33:]
		}
		lines := bakedOverride(short, sub)
		if len(lines) == 0 {
			continue
		}
		dst := filepath.Join(b.AppDir, "store", short, sub)
		if _, err := os.Stat(dst); err != nil {
			if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
				continue
			}
			if err := copyTreeNoClobber(src, dst); err != nil {
				continue
			}
		}
		out = append(out, lines...)
		for _, l := range lines {
			name, _, _ := strings.Cut(l, "=")
			vars = append(vars, name)
		}
		nCarried++
	}
	logx.Say("baked paths %d strings, %d naming a real directory, %d carried",
		len(refs), nDir, nCarried)
	if len(vars) > 0 {
		logx.Say("overrides   %s", strings.Join(uniq(vars), " "))
	}
	return out
}
