#!/usr/bin/env python3
"""Generate the forwarding table for one SONAME the shim impersonates.

The shim replaces a bundled library wholesale (see src/gl-fwd.c), so the one
correctness rule is: IT MUST EXPORT EVERYTHING THE LIBRARY IT REPLACES
EXPORTS.  Anything less and an application that links a symbol outside the
list fails with `undefined symbol` -- at load time under BIND_NOW, at first
call otherwise.  So the list is READ OUT of the library being replaced rather
than written by hand.

    tools/gen_gl_fwd.py <bundled.so> --prefix gl --out src/gl-fwd-gl.h
    tools/gen_gl_fwd.py <bundled.so> --prefix gl --check src/gl-fwd-gl.h

--check is the regression gate: it re-reads the library and fails if the
checked-in table no longer matches, so a newer bundled libglvnd cannot add an
entry point silently.
"""
import argparse, hashlib, os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from elfsym import Elf


def exported_functions(path):
    """Defined, default-visibility FUNC exports, plus the ones we refuse.

    IFUNCs are included: an IFUNC export is called exactly like a function and
    the resolver runs in the DEFINING object, so forwarding to the address
    dlsym hands back is correct.  Data objects are NOT: a trampoline cannot
    forward an object, and forwarding the wrong shape silently is worse than
    declining loudly, so they are returned separately and reported.
    """
    e = Elf(path)
    funcs, data = set(), set()
    for s in e.symbols():
        if s['shndx'] == 0 or s['bind'] not in ('GLOBAL', 'WEAK') or s['vis'] != 0:
            continue
        if s['type'] in ('FUNC', 'GNU_IFUNC'):
            funcs.add(s['name'])
        elif s['type'] == 'OBJECT':
            data.add(s['name'])
    return e, funcs, data


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('library', help='the bundled .so whose SONAME the shim takes over')
    ap.add_argument('--prefix', action='append', default=[],
                    help='only forward names with this prefix (repeatable)')
    ap.add_argument('--out', help='write the table here')
    ap.add_argument('--check', help='compare against this existing table instead')
    ap.add_argument('--soname', help='override the SONAME read from the library')
    args = ap.parse_args()

    e, funcs, data = exported_functions(args.library)
    soname = args.soname or e.soname()
    if not soname:
        sys.exit(f'{args.library}: no DT_SONAME, and none given with --soname')

    prefixes = tuple(args.prefix) if args.prefix else ()
    kept = sorted(n for n in funcs if not prefixes or n.startswith(prefixes))
    dropped = sorted(n for n in funcs if prefixes and not n.startswith(prefixes))

    # Every kept name becomes an assembler label and a C token. glibc puts
    # VERSION NAMES in .dynsym as zero-sized SHN_ABS entries (GLIBC_2.32,
    # GLIBC_ABI_DT_RELR) and a generator that treats those as symbols emits
    # identifiers containing a dot. That already happened once in this
    # repository, to gen_forward_shim.py, and the failure was a wall of
    # assembler errors rather than a sentence. Refuse here instead.
    bad = [n for n in kept if not re.match(r'^[A-Za-z_][A-Za-z0-9_]*$', n)]
    if bad:
        sys.exit(f'{args.library}: {len(bad)} exported name(s) are not valid '
                 f'identifiers and cannot become trampolines: ' +
                 ', '.join(bad[:6]))

    sha = hashlib.sha256(open(args.library, 'rb').read()).hexdigest()[:16]
    lines = []
    lines.append('/* GENERATED by tools/gen_gl_fwd.py. Do not edit.')
    lines.append(' *')
    lines.append(f' * source   : {os.path.basename(args.library)}  (sha256 {sha}...)')
    lines.append(f' * soname   : {soname}')
    lines.append(f' * exports  : {len(kept)} forwarded'
                 + (f', {len(dropped)} outside --prefix {"/".join(prefixes)}' if dropped else ''))
    if data:
        lines.append(f' * data     : {len(data)} exported OBJECT symbols NOT forwarded: '
                     + ', '.join(sorted(data)[:8]) + ('...' if len(data) > 8 else ''))
        lines.append(' *            A trampoline forwards a call, not a variable. If an')
        lines.append(' *            application ever links one of these the shim cannot')
        lines.append(' *            stand in for it, and it fails loudly, which is right.')
    lines.append(' */')
    lines.append('/* The table is included several times, once per generated')
    lines.append(' * artefact (slot initialiser, trampolines, name table), so the')
    lines.append(' * scalars are guarded and only the GLFWD_SYM lines re-expand. */')
    lines.append('#ifndef GLFWD_SONAME')
    lines.append(f'#define GLFWD_SONAME  "{soname}"')
    lines.append(f'#define GLFWD_COUNT   {len(kept)}')
    lines.append('#endif')
    for i, n in enumerate(kept):
        lines.append(f'GLFWD_SYM({i}, {n})')
    text = '\n'.join(lines) + '\n'

    if args.check:
        have = open(args.check).read() if os.path.exists(args.check) else ''
        # The sha line is provenance, not content: compare the table itself.
        strip = lambda t: '\n'.join(l for l in t.splitlines() if 'sha256' not in l)
        if strip(have) != strip(text):
            sys.stderr.write(
                f'{args.check}: STALE.\n'
                f'  the table checked in does not match {args.library}.\n'
                f'  regenerate with:  cd src && make gl-syms GLVND=<AppDir>/lib\n')
            hs = set(l.split('(')[1].split(',')[1].strip(' )')
                     for l in have.splitlines() if l.startswith('GLFWD_SYM('))
            ns = set(kept)
            for what, s in (('only in the library', ns - hs), ('only in the table', hs - ns)):
                if s:
                    sys.stderr.write(f'  {what}: {len(s)} -- ' +
                                     ', '.join(sorted(s)[:6]) + '\n')
            return 1
        print(f'ok: {args.check} matches {os.path.basename(args.library)} '
              f'({len(kept)} entry points)')
        return 0

    if args.out:
        open(args.out, 'w', newline='\n').write(text)
        print(f'{args.out}: {len(kept)} entry points from {os.path.basename(args.library)}')
    else:
        sys.stdout.write(text)
    return 0


if __name__ == '__main__':
    sys.exit(main())
