//! The manifest describing how to drive this soar.
//!
//! A frontend that shells out to soar needs to know which arguments to pass and
//! how to read what comes back. Shipping that description in the binary keeps
//! the two from falling out of step.

/// The manifest format. A reader should refuse a version it does not know.
const SCHEMA_VERSION: u32 = 1;

/// The manifest, with `@schema_version@`, `@version@` and `@profiles@` filled
/// in by [`manifest`].
const TEMPLATE: &str = r#"# Generated by `soar plugin-manifest`. This describes the soar that
# emitted it, so it is worth regenerating rather than copying between machines.
schema_version = @schema_version@
id = "soar"
name = "Soar"
version = "@version@"

# Most specific form first: a package published under a family is named by it,
# and one published without a family is named on its own.
selector = ["{family}/{name}", "{name}"]

# Soar manages a separate set of packages for everyone, reached with the same
# command and one more flag. It elevates itself when it has to, which a window
# cannot answer, so it is run elevated instead.
[system]
args = ["--system"]
elevate = true

[detect]
command = "soar"
version = ["--version"]
min_version = "@version@"

# The settings, as they are named in the configuration file. A frontend reads
# and writes that file directly, so this says what is in it rather than
# standing in front of it.
[[config]]
key = "parallel"
label = "Parallel downloads"
type = "toggle"
default = true

[[config]]
key = "parallel_limit"
label = "Parallel limit"
type = "number"
default = 4

[[config]]
key = "search_limit"
label = "Search result limit"
type = "number"
default = 20

[[config]]
key = "signature_verification"
label = "Signature verification"
type = "toggle"
default = true

[[config]]
key = "desktop_integration"
label = "Desktop integration"
type = "toggle"
default = false

[[config]]
key = "bin_path"
label = "Bin path"
type = "path_list"
section = "Paths"

[[config]]
key = "cache_path"
label = "Cache path"
type = "path_list"
section = "Paths"

[[config]]
key = "db_path"
label = "DB path"
type = "path_list"
section = "Paths"

[[config]]
key = "desktop_path"
label = "Desktop path"
type = "path_list"
section = "Paths"

[[config]]
key = "repositories_path"
label = "Repos path"
type = "path_list"
section = "Paths"

[[config]]
key = "portable_dirs"
label = "Portable dirs"
type = "path_list"
section = "Paths"

[[config]]
key = "sync_interval"
label = "Sync interval"
type = "text"
section = "Advanced"

[[config]]
key = "default_profile"
label = "Default profile"
type = "select"
options = [@profiles@]
default = "default"
section = "Advanced"

# Query commands answer with one JSON document; `items` is the array to read
# and `total` says how many matched before any limit was applied.
[ops.list]
args = ["--json", "list"]
output = { format = "json", select = "$.items[*]" }
fields = { name = "name", family = "family", version = "version", repo = "repo", description = "description", size = "size", installed = "installed" }

[ops.list_installed]
args = ["--json", "info"]
output = { format = "json", select = "$.items[*]" }
fields = { name = "name", family = "family", version = "version", repo = "repo", size = "disk_size", path = "installed_path", installed_at = "installed_date", pinned = "pinned", healthy = "healthy" }

[ops.search]
args = ["--json", "search", "{query}"]
output = { format = "json", select = "$.items[*]" }
fields = { name = "name", family = "family", version = "version", repo = "repo", description = "description", size = "size", installed = "installed" }

[ops.info]
args = ["--json", "query", "{selector}"]
output = { format = "json", select = "$.items[*]" }
fields = { name = "name", family = "family", version = "version", repo = "repo", description = "description", size = "size", checksum = "checksum", homepage = "homepages", license = "licenses", category = "categories", pkg_type = "pkg_type", source = "source_urls", build_date = "build_date", download_url = "download_url" }

# Everything else soar knows about a package. A frontend shows these as
# given, so the labels are what a reader sees.
[[ops.info.extra]]
label = "Maintainer"
field = "maintainers"

[[ops.info.extra]]
label = "Checksum"
field = "checksum"

[ops.list_updates]
args = ["--json", "update", "--check"]
output = { format = "json", select = "$.items[*]" }
fields = { name = "name", family = "family", repo = "repo", version = "current_version", current_version = "current_version", new_version = "new_version", size = "size" }

[ops.list_repos]
args = ["--json", "repo", "list"]
output = { format = "json", select = "$.items[*]" }
fields = { name = "name", url = "url", enabled = "enabled" }

# Where soar keeps its files, so they can be read and written directly rather
# than through a command for every field.
[ops.paths]
args = ["--json", "env"]
output = { format = "json" }
fields = { config = "config", packages_config = "packages_config", bin = "bin", db = "db", cache = "cache", packages = "packages", repositories = "repositories" }

# What applying the declarative configuration would change, asked before it is
# applied rather than reported while it happens.
# Always pruning, so the answer says which installed packages are undeclared.
# Whether they are actually removed is decided when applying.
[ops.apply_check]
args = ["--json", "apply", "--dry-run", "--prune"]
output = { format = "json" }

# Operations answer with a stream instead: one JSON object per line, written as
# it happens, so progress can be shown while the work is still running.
[ops.install]
args = ["--json", "install", "--yes", "{selector}"]
output = { format = "ndjson" }
progress = { event = "type", stage = "stage", current = "current", total = "total", message = "pkg_name" }

[ops.remove]
args = ["--json", "remove", "--yes", "{selector}"]
output = { format = "ndjson" }
progress = { event = "type", stage = "stage", message = "pkg_name" }

[ops.update]
args = ["--json", "update", "{selector}"]
output = { format = "ndjson" }
progress = { event = "type", stage = "stage", current = "current", total = "total", message = "pkg_name" }

[ops.update_all]
args = ["--json", "update"]
output = { format = "ndjson" }
progress = { event = "type", stage = "stage", current = "current", total = "total", message = "pkg_name" }

[ops.sync]
args = ["--json", "sync"]
output = { format = "ndjson" }
progress = { event = "type", stage = "stage", message = "repo_name" }

# Pruning is a different command rather than a flag on this one, because an
# operation is one argv and nothing here is conditional.
[ops.apply]
args = ["--json", "apply", "--yes"]
output = { format = "ndjson" }
progress = { event = "type", stage = "stage", current = "current", total = "total", message = "pkg_name" }

[ops.apply_prune]
args = ["--json", "apply", "--yes", "--prune"]
output = { format = "ndjson" }
progress = { event = "type", stage = "stage", current = "current", total = "total", message = "pkg_name" }

# Writing a first configuration file. Soar needs a whole one to start from,
# so a frontend meaning to edit settings asks for this before writing any.
[ops.default_config]
args = ["defconfig"]
output = { format = "ndjson" }

# Repository commands report nothing on success, so there is no shape to read.
[ops.add_repo]
args = ["repo", "add", "{name}", "{url}"]
output = { format = "ndjson" }

[ops.remove_repo]
args = ["repo", "remove", "{name}"]
output = { format = "ndjson" }

[ops.set_repo_enabled]
args = ["repo", "update", "{name}", "--enabled", "{enabled}"]
output = { format = "ndjson" }
"#;

/// Describes soar's commands as this build accepts them.
///
/// `{selector}`, `{name}`, `{query}` and `{version}` are the only substitutions
/// a caller makes; `selector` says how to build the first from a package's
/// fields. `profiles` are the ones this machine has, which is why the manifest
/// is generated rather than shipped as a file.
pub fn manifest(profiles: &[String]) -> String {
    let options = profiles
        .iter()
        .map(|profile| format!("{profile:?}"))
        .collect::<Vec<_>>()
        .join(", ");

    TEMPLATE
        .replace("@schema_version@", &SCHEMA_VERSION.to_string())
        .replace("@version@", env!("CARGO_PKG_VERSION"))
        .replace("@profiles@", &options)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_manifest_is_valid_toml() {
        let parsed: toml::Value =
            toml::from_str(&manifest(&["default".into()])).expect("manifest must parse");
        assert_eq!(parsed["schema_version"].as_integer(), Some(1));
        assert_eq!(parsed["id"].as_str(), Some("soar"));
    }

    #[test]
    fn every_operation_names_a_real_subcommand() {
        use clap::CommandFactory;

        let parsed: toml::Value = toml::from_str(&manifest(&["default".into()])).unwrap();
        let known: Vec<String> = crate::cli::Args::command()
            .get_subcommands()
            .map(|sub| sub.get_name().to_string())
            .collect();

        for (op, table) in parsed["ops"].as_table().expect("ops table") {
            let args = table["args"].as_array().expect("args array");
            // The first argument that is not a global flag is the subcommand.
            let subcommand = args
                .iter()
                .filter_map(|a| a.as_str())
                .find(|a| !a.starts_with('-'))
                .unwrap_or_else(|| panic!("{op} names no subcommand"));
            assert!(
                known.iter().any(|k| k == subcommand),
                "{op} runs `{subcommand}`, which this soar does not have"
            );
        }
    }
}
