//! The report: tables, graphs, rankings, and what the run did NOT establish.
//!
//! ⭐ THE REPORT OPENS WITH WHAT IT COULD NOT SHOW. Not in an appendix, not
//! after the recommendation — first, where a reader skimming for the answer
//! cannot miss it. Failed cells, unsupported configurations, noisy
//! measurements and missing controls come before any ranking.

use crate::model::*;
use crate::rank::{self, Row};
use crate::svg;
use crate::validate::{Finding, Severity};
use std::collections::BTreeMap;
use std::fmt::Write;
use std::path::Path;

fn f3(v: Option<f64>) -> String {
    match v {
        // ⛔ A dash where the value is unknown. Never a zero, never a blank
        // that could be read as one.
        None => "–".into(),
        Some(x) if !x.is_finite() => "–".into(),
        Some(x) => format!("{:.3}", x),
    }
}
fn pct(v: Option<f64>) -> String {
    match v {
        None => "–".into(),
        Some(x) if !x.is_finite() => "–".into(),
        Some(x) => format!("{:.1}%", x * 100.0),
    }
}
fn mib(v: Option<u64>) -> String {
    match v {
        None => "–".into(),
        Some(b) => format!("{:.2}", b as f64 / (1024.0 * 1024.0)),
    }
}

pub struct Report {
    pub markdown: String,
    pub charts: BTreeMap<String, String>,
    pub rankings_json: String,
}

pub fn build(
    meta: &RunMeta,
    plan: &[Cell],
    results: &[CellResult],
    findings: &[Finding],
    workload: &str,
) -> Report {
    let mut m = String::new();
    let groups = rank::build_rows(results, workload);
    let verdicts = rank::verdicts(&groups);

    let ok = results.iter().filter(|r| r.rankable()).count();
    let unsupported: Vec<&CellResult> = results
        .iter()
        .filter(|r| r.outcome == "unsupported")
        .collect();
    let failed: Vec<&CellResult> = results
        .iter()
        .filter(|r| r.outcome != "ok" && r.outcome != "unsupported")
        .collect();

    // ---------------------------------------------------------------- header
    let _ = writeln!(m, "# Allocator benchmark — run `{}`\n", meta.run_id);
    let _ = writeln!(
        m,
        "Generated by `alloc-bench report`. ⛔ Do not edit: it is overwritten from the dataset in `results/`.\n"
    );

    // ------------------------------------------- what this run did NOT show
    let _ = writeln!(m, "## What this run does not establish\n");
    let _ = writeln!(
        m,
        "Read this before the tables. It is not a disclaimer; it is the list of \
         questions these numbers cannot answer.\n"
    );
    let _ = writeln!(m, "| | |");
    let _ = writeln!(m, "| --- | --- |");
    let _ = writeln!(
        m,
        "| **one machine, one day** | `{}`, {} × `{}`, {} MiB RAM, kernel `{}`. Absolute timings here do not transfer to other hardware. Ratios within a group are the transferable part, and even those are measured, not guaranteed. |",
        meta.host.cpu_model,
        meta.host.cpu_count,
        meta.host.arch,
        meta.host.mem_total_kb / 1024,
        meta.host.kernel
    );
    let _ = writeln!(
        m,
        "| **cells that could not exist** | {} configuration(s) are unsupported, each with a recorded technical reason. They are listed below rather than dropped. |",
        unsupported.len()
    );
    let _ = writeln!(
        m,
        "| **cells that failed** | {} configuration(s) were attempted and did not produce a usable result. Also listed below. |",
        failed.len()
    );
    if meta.host.emulated {
        let _ = writeln!(
            m,
            "| ⛔ **emulated** | the target architecture is not the host's, so this ran under binfmt emulation. Timings are recorded and **excluded from ranking**: emulation changes the instruction mix and the memory behaviour, so the comparison would measure the emulator. |"
        );
    }
    let noisy: Vec<&Finding> = findings.iter().filter(|f| f.check == "noisy").collect();
    if !noisy.is_empty() {
        let _ = writeln!(
            m,
            "| **noise** | {} cell(s) measured a relative MAD above the {:.0}% threshold. Differences smaller than that cell's own spread are not attributable to the allocator. |",
            noisy.len(),
            crate::validate::NOISE_REL_MAD_WARN * 100.0
        );
    }
    let _ = writeln!(
        m,
        "| **what an allocator is good at generally** | this measures one application (ripgrep) on one corpus shape. ripgrep is not allocation-bound; an allocation-heavy service would rank differently, and nothing here says otherwise. |"
    );
    let _ = writeln!(
        m,
        "| **security** | hardened_malloc trades performance for memory-safety mitigations. A slower row for it is the expected cost of what it does, not a defect, and this project makes no claim about whether those mitigations work. |\n"
    );

    // ------------------------------------------------------------ conditions
    let _ = writeln!(m, "## Conditions\n");
    let _ = writeln!(m, "| | |");
    let _ = writeln!(m, "| --- | --- |");
    let _ = writeln!(m, "| run id | `{}` |", meta.run_id);
    let _ = writeln!(m, "| started | {} |", meta.started_at);
    let _ = writeln!(m, "| suites | {} |", meta.suites.join(", "));
    let _ = writeln!(m, "| repository commit | `{}` |", meta.git_commit);
    let _ = writeln!(m, "| corpus seed | `{}` |", meta.corpus_seed);
    let _ = writeln!(
        m,
        "| container runtime | {} {} |",
        meta.host.container_runtime, meta.host.runtime_version
    );
    let _ = writeln!(m, "| primary workload | `{}` |", workload);
    for (k, v) in &meta.ci {
        let _ = writeln!(m, "| {} | `{}` |", k, v);
    }
    let _ = writeln!(m);

    // ------------------------------------------------------- pinned versions
    let _ = writeln!(m, "### Exactly what produced these numbers\n");
    let _ = writeln!(m, "| component | ref | commit |");
    let _ = writeln!(m, "| --- | --- | --- |");
    for (id, e) in &meta.lock.entries {
        let _ = writeln!(
            m,
            "| `{}` | {} `{}` | [`{}`]({}/commit/{}) |",
            id,
            e.kind,
            e.reference,
            &e.commit[..e.commit.len().min(12)],
            e.repo,
            e.commit
        );
    }
    let _ = writeln!(m);

    // --------------------------------------------------------------- results
    let _ = writeln!(m, "## Rankings\n");
    let _ = writeln!(
        m,
        "Ordered by median execution time on `{}`, fastest first. `rel` is the ratio against \
         the control in the SAME image, architecture, profile and toolchain — no ratio crosses a group. \
         `MAD` is the relative median absolute deviation of that cell's own samples: **a difference \
         smaller than the MAD is not a result**.\n",
        workload
    );
    let _ = writeln!(
        m,
        "Composite, where shown: `{}`.\n",
        rank::COMPOSITE_FORMULA
    );

    let mut charts: BTreeMap<String, String> = BTreeMap::new();

    for (g, rows) in &groups {
        let _ = writeln!(m, "### {}\n", g);
        let _ = writeln!(
            m,
            "| # | allocator | mechanism | time (s) | rel | MAD | peak RSS (MiB) | rel | size (MiB) | startup (s) | composite |"
        );
        let _ = writeln!(
            m,
            "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"
        );
        for (i, r) in rows.iter().enumerate() {
            let _ = writeln!(
                m,
                "| {} | {}{} | `{}` | {} | {} | {} | {} | {} | {} | {} | {} |",
                i + 1,
                r.allocator,
                if r.is_baseline { " *(control)*" } else { "" },
                r.integration,
                f3(r.time_s),
                f3(r.rel_time),
                pct(r.rel_mad),
                f3(r.rss_kb.map(|v| v / 1024.0)),
                f3(r.rel_rss),
                mib(r.size_bytes),
                f3(r.startup_s),
                f3(r.composite),
            );
        }
        let _ = writeln!(m);

        if let Some(v) = verdicts.iter().find(|v| &v.group == g) {
            if v.within_noise {
                let _ = writeln!(m, "> ⚠ **No winner is claimed here.** {}\n", v.note);
            } else {
                let _ = writeln!(
                    m,
                    "> **Fastest: {}.** {}\n",
                    v.winner.clone().unwrap_or_else(|| "–".into()),
                    v.note
                );
            }
        }

        let slug = g.replace([' ', '/'], "").replace("--", "-");
        if let Some(c) = svg::relative_time_chart(g, rows, workload) {
            charts.insert(format!("time-{}.svg", slug), c);
            let _ = writeln!(m, "![relative time](time-{}.svg)\n", slug);
        }
        if let Some(c) = svg::relative_rss_chart(g, rows, workload) {
            charts.insert(format!("rss-{}.svg", slug), c);
            let _ = writeln!(m, "![relative peak RSS](rss-{}.svg)\n", slug);
        }
        if let Some(c) = svg::size_chart(g, rows) {
            charts.insert(format!("size-{}.svg", slug), c);
            let _ = writeln!(m, "![binary size](size-{}.svg)\n", slug);
        }
    }

    // ------------------------------------------------------ every workload
    let _ = writeln!(m, "## Every workload\n");
    let _ = writeln!(
        m,
        "The ranking above uses one workload. These are all of them, as median seconds, \
         so a reader can see whether the ordering holds or whether it is an artefact of one shape of work.\n"
    );
    let mut workloads: Vec<String> = results
        .iter()
        .flat_map(|r| r.measurements.keys().cloned())
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect();
    workloads.sort();
    if !workloads.is_empty() {
        let _ = writeln!(m, "| cell | {} |", workloads.join(" | "));
        let _ = writeln!(m, "| --- |{}", " --- |".repeat(workloads.len()));
        for r in results.iter().filter(|r| r.rankable()) {
            let cells: Vec<String> = workloads.iter().map(|w| f3(r.median_wall(w))).collect();
            let _ = writeln!(m, "| `{}` | {} |", r.cell.id, cells.join(" | "));
        }
        let _ = writeln!(m);
    }

    // ------------------------------------------------------------- ASLR
    let aslr_rows: Vec<&CellResult> = results
        .iter()
        .filter(|r| r.rankable() && r.aslr.is_some())
        .collect();
    if !aslr_rows.is_empty() {
        let _ = writeln!(m, "## Address-space randomisation, observed\n");
        let _ = writeln!(
            m,
            "Read from `/proc/<pid>/maps` while each binary was running, not inferred from the ELF type. \
             A static non-PIE executable is loaded at a fixed address; a static PIE is not.\n"
        );
        let _ = writeln!(
            m,
            "| cell | profile | link kind | distinct load addresses | randomised |"
        );
        let _ = writeln!(m, "| --- | --- | --- | --- | --- |");
        for r in aslr_rows {
            let a = r.aslr.as_ref().unwrap();
            let kind = r
                .identity
                .as_ref()
                .and_then(|v| v.get("link_kind"))
                .and_then(|v| v.as_str())
                .unwrap_or("–");
            let _ = writeln!(
                m,
                "| `{}` | {} | {} | {} of {} | {} |",
                r.cell.id,
                r.cell.profile,
                kind,
                a.get("distinct_bases")
                    .and_then(|v| v.as_u64())
                    .unwrap_or(0),
                a.get("sampled").and_then(|v| v.as_u64()).unwrap_or(0),
                a.get("randomised")
                    .and_then(|v| v.as_bool())
                    .unwrap_or(false)
            );
        }
        let _ = writeln!(m);
    }

    // ------------------------------------------------- unsupported and failed
    let _ = writeln!(m, "## Configurations that could not exist\n");
    if unsupported.is_empty() {
        let _ = writeln!(m, "None in this run.\n");
    } else {
        let _ = writeln!(
            m,
            "⭐ These are results. Each names a concrete technical reason, and a future upstream \
             release that removes the reason turns the row into a measurement without anyone editing prose.\n"
        );
        let _ = writeln!(m, "| cell | reason |");
        let _ = writeln!(m, "| --- | --- |");
        for r in &unsupported {
            let _ = writeln!(
                m,
                "| `{}` | {} |",
                r.cell.id,
                r.detail
                    .as_deref()
                    .unwrap_or("⛔ no reason recorded — this is itself a defect")
                    .replace('\n', " ")
            );
        }
        let _ = writeln!(m);
    }

    let _ = writeln!(m, "## Configurations that failed\n");
    if failed.is_empty() {
        let _ = writeln!(m, "None in this run.\n");
    } else {
        let _ = writeln!(m, "| cell | outcome | detail |");
        let _ = writeln!(m, "| --- | --- | --- |");
        for r in &failed {
            let _ = writeln!(
                m,
                "| `{}` | `{}` | {} |",
                r.cell.id,
                r.outcome,
                r.detail
                    .as_deref()
                    .unwrap_or("no detail recorded")
                    .replace('\n', " ")
                    .chars()
                    .take(400)
                    .collect::<String>()
            );
        }
        let _ = writeln!(m);
    }

    // ------------------------------------------------------------ validation
    let _ = writeln!(m, "## Validation\n");
    let _ = writeln!(
        m,
        "`alloc-bench validate` checks the dataset before this report is written. \
         An `ERROR` means the ranking above must not be trusted; the exit status reflects it.\n"
    );
    let _ = writeln!(m, "| severity | check | cell | message |");
    let _ = writeln!(m, "| --- | --- | --- | --- |");
    if findings.is_empty() {
        let _ = writeln!(m, "| info | all | – | every check passed |");
    }
    for f in findings {
        let _ = writeln!(
            m,
            "| {} | `{}` | {} | {} |",
            f.severity.as_str(),
            f.check,
            f.cell
                .as_deref()
                .map(|c| format!("`{}`", c))
                .unwrap_or_else(|| "–".into()),
            f.message
                .replace('\n', " ")
                .chars()
                .take(400)
                .collect::<String>()
        );
    }
    let _ = writeln!(m);

    let _ = writeln!(
        m,
        "---\n\n{} cell(s) planned, {} produced a usable result, {} unsupported, {} failed.\n",
        plan.len(),
        ok,
        unsupported.len(),
        failed.len()
    );
    let _ = writeln!(
        m,
        "Raw samples, build metadata, identity evidence and correctness output for every cell are in \
         `results/` and `cells/` beside this file. ⭐ Every number above is derived from them; none was typed in."
    );

    let rankings_json = serde_json::to_string_pretty(&serde_json::json!({
        "run_id": meta.run_id,
        "primary_workload": workload,
        "composite_formula": rank::COMPOSITE_FORMULA,
        "groups": groups.iter().map(|(g, rows)| {
            serde_json::json!({
                "group": g,
                "rows": rows.iter().map(row_json).collect::<Vec<_>>(),
            })
        }).collect::<Vec<_>>(),
        "verdicts": verdicts.iter().map(|v| serde_json::json!({
            "group": v.group,
            "winner": v.winner,
            "margin_pct": v.margin_pct,
            "within_noise": v.within_noise,
            "note": v.note,
        })).collect::<Vec<_>>(),
        "findings": findings.iter().map(|f| serde_json::json!({
            "severity": f.severity.as_str(),
            "check": f.check,
            "cell": f.cell,
            "message": f.message,
        })).collect::<Vec<_>>(),
    }))
    .unwrap_or_else(|_| "{}".into());

    Report {
        markdown: m,
        charts,
        rankings_json,
    }
}

fn row_json(r: &Row) -> serde_json::Value {
    serde_json::json!({
        "cell_id": r.cell_id,
        "distro": r.distro,
        "arch": r.arch,
        "allocator": r.allocator,
        "integration": r.integration,
        "profile": r.profile,
        "toolchain": r.toolchain,
        "time_s": r.time_s,
        "rel_time": r.rel_time,
        "rel_mad": r.rel_mad,
        "rss_kb": r.rss_kb,
        "rel_rss": r.rel_rss,
        "size_bytes": r.size_bytes,
        "rel_size": r.rel_size,
        "startup_s": r.startup_s,
        "composite": r.composite,
        "is_baseline": r.is_baseline,
    })
}

pub fn write(dir: &Path, r: &Report) -> Result<(), String> {
    std::fs::create_dir_all(dir).map_err(|e| format!("{}: {}", dir.display(), e))?;
    std::fs::write(dir.join("report.md"), &r.markdown).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("rankings.json"), &r.rankings_json).map_err(|e| e.to_string())?;
    for (name, svg) in &r.charts {
        std::fs::write(dir.join(name), svg).map_err(|e| format!("{}: {}", name, e))?;
    }
    Ok(())
}

pub fn severity_summary(findings: &[Finding]) -> (usize, usize) {
    (
        findings
            .iter()
            .filter(|f| f.severity == Severity::Error)
            .count(),
        findings
            .iter()
            .filter(|f| f.severity == Severity::Warn)
            .count(),
    )
}
