FROM alpine:latest

# Update repositories to edge
RUN echo https://dl-cdn.alpinelinux.org/alpine/edge/main/      >  /etc/apk/repositories
RUN echo https://dl-cdn.alpinelinux.org/alpine/edge/community/ >> /etc/apk/repositories
RUN echo https://dl-cdn.alpinelinux.org/alpine/edge/testing/   >> /etc/apk/repositories

# Install deps for MkDocs
RUN apk update && apk upgrade
RUN apk add --no-cache build-base cmake python3 py3-pip py3-virtualenv git

# Copy project directory
COPY . /flatroot
WORKDIR /flatroot

# Create virtual environment and install MkDocs packages
RUN python3 -m venv /flatroot/docs/mkdocs/env && \
    /flatroot/docs/mkdocs/env/bin/python3 -m ensurepip --upgrade && \
    /flatroot/docs/mkdocs/env/bin/python3 -m pip install --upgrade pip && \
    /flatroot/docs/mkdocs/env/bin/python3 -m pip install \
        mkdocs mkdocs-material mkdocs-mermaid2-plugin \
        mkdocs-panzoom-plugin mkdocs-drawio mkdocs-macros-plugin mike \
        git+https://github.com/ruanformigoni/mkdocs-material-footer-tags.git@v0.1.0

# MkDocs URL variables (passed as build args from compose); default to the
# public GitHub URLs so unparameterized builds match mkdocs.yml/main.py.
ARG FLATROOT_RELEASE_URL=https://github.com/flatroot/flatroot/releases/latest/download
ARG FLATROOT_REPO_URL=https://github.com/flatroot/flatroot
ENV FLATROOT_RELEASE_URL=$FLATROOT_RELEASE_URL
ENV FLATROOT_REPO_URL=$FLATROOT_REPO_URL

# Build MkDocs documentation
RUN cd /flatroot/docs/mkdocs && \
    /flatroot/docs/mkdocs/env/bin/mkdocs build

# Move site to a top-level location matching flatimage's convention.
RUN mv /flatroot/docs/mkdocs/site /flatroot/site
