name: archlinux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  archlinux:

    runs-on: ubuntu-latest

    container: archlinux

    steps:
      - uses: actions/checkout@main

      - run:  ./build.sh

      - run:  ./elftool

      - run:  ./elftool --help
      - run:  ./elftool --version

      - run:  ./elftool -h
      - run:  ./elftool -V

      - run:  ./elftool print-interp elftool
      - run:  ./elftool print-soname elftool
      - run:  ./elftool print-needed elftool
      - run:  ./elftool print-rpath  elftool
