name: Manjaro Linux

on:
  push:
    branches: [ master, dev, tmp ]
  pull_request:
    branches: [ master, dev, tmp ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    container: manjarolinux/base

    steps:
      - uses: actions/checkout@main

      - run:  ./build.sh

      - run:  ./elftool

      - run:  ./elftool --help
      - run:  ./elftool --version

      - run:  ./elftool -h
      - run:  ./elftool -V

      - run:  ./elftool print-interp elftool
      - run:  ./elftool print-soname elftool
      - run:  ./elftool print-needed elftool
      - run:  ./elftool print-rpath  elftool
