name: NetBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        netbsd-version: ['10.1', '10.0', '9.4', '9.3', '9.2']

    steps:
      - uses: actions/checkout@v5

      - uses: cross-platform-actions/action@master
        with:
          operating_system: netbsd
          version: ${{ matrix.netbsd-version }}
          shell: bash
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            run ./build.sh

            run ./elftool

            run ./elftool --help
            run ./elftool --version

            run ./elftool -h
            run ./elftool -V

            run ./elftool print-interp elftool
            run ./elftool print-soname elftool
            run ./elftool print-needed elftool
            run ./elftool print-rpath  elftool
