name: openEuler

on:
  push:
    branches: [ master, dev, tmp ]
  pull_request:
    branches: [ master, dev, tmp ]

jobs:
  openeuler:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tag: ['24.03']

    container: openeuler/openeuler:${{ matrix.tag }}

    steps:
      - uses: actions/checkout@main

      - run:  ./build.sh

      - run:  ./elftool

      - run:  ./elftool --help
      - run:  ./elftool --version

      - run:  ./elftool -h
      - run:  ./elftool -V

      - run:  ./elftool print-interp elftool
      - run:  ./elftool print-soname elftool
      - run:  ./elftool print-needed elftool
      - run:  ./elftool print-rpath  elftool
