name: voidlinux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  voidlinux:
    strategy:
      fail-fast: false
      matrix:
        variant: ['voidlinux', 'voidlinux-musl']

    runs-on: ubuntu-latest

    container: voidlinux/${{ matrix.variant }}

    steps:
      # SSL certificate subject doesn't match host alpha.de.repo.voidlinux.org
      # ERROR: [reposync] failed to fetch file `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata': Operation not permitted
      - run: sed -i s/alpha.de.repo.voidlinux.org/repo-default.voidlinux.org/g /usr/share/xbps.d/*

      # https://github.com/actions/checkout/issues/334
      - uses: actions/checkout@v1

      - run:  ./build.sh

      - run:  ./elftool

      - run:  ./elftool --help
      - run:  ./elftool --version

      - run:  ./elftool -h
      - run:  ./elftool -V

      - run:  ./elftool print-interp elftool
      - run:  ./elftool print-soname elftool
      - run:  ./elftool print-needed elftool
      - run:  ./elftool print-rpath  elftool
