/* GENERATED by tools/gen_gl_fwd.py. Do not edit.
 *
 * source   : libEGL.so.1.1.0  (sha256 3890d9f23603dcbf...)
 * soname   : libEGL.so.1
 * exports  : 44 forwarded
 */
/* The table is included several times, once per generated
 * artefact (slot initialiser, trampolines, name table), so the
 * scalars are guarded and only the GLFWD_SYM lines re-expand. */
#ifndef GLFWD_SONAME
#define GLFWD_SONAME  "libEGL.so.1"
#define GLFWD_COUNT   44
#endif
GLFWD_SYM(0, eglBindAPI)
GLFWD_SYM(1, eglBindTexImage)
GLFWD_SYM(2, eglChooseConfig)
GLFWD_SYM(3, eglClientWaitSync)
GLFWD_SYM(4, eglCopyBuffers)
GLFWD_SYM(5, eglCreateContext)
GLFWD_SYM(6, eglCreateImage)
GLFWD_SYM(7, eglCreatePbufferFromClientBuffer)
GLFWD_SYM(8, eglCreatePbufferSurface)
GLFWD_SYM(9, eglCreatePixmapSurface)
GLFWD_SYM(10, eglCreatePlatformPixmapSurface)
GLFWD_SYM(11, eglCreatePlatformWindowSurface)
GLFWD_SYM(12, eglCreateSync)
GLFWD_SYM(13, eglCreateWindowSurface)
GLFWD_SYM(14, eglDestroyContext)
GLFWD_SYM(15, eglDestroyImage)
GLFWD_SYM(16, eglDestroySurface)
GLFWD_SYM(17, eglDestroySync)
GLFWD_SYM(18, eglGetConfigAttrib)
GLFWD_SYM(19, eglGetConfigs)
GLFWD_SYM(20, eglGetCurrentContext)
GLFWD_SYM(21, eglGetCurrentDisplay)
GLFWD_SYM(22, eglGetCurrentSurface)
GLFWD_SYM(23, eglGetDisplay)
GLFWD_SYM(24, eglGetError)
GLFWD_SYM(25, eglGetPlatformDisplay)
GLFWD_SYM(26, eglGetProcAddress)
GLFWD_SYM(27, eglGetSyncAttrib)
GLFWD_SYM(28, eglInitialize)
GLFWD_SYM(29, eglMakeCurrent)
GLFWD_SYM(30, eglQueryAPI)
GLFWD_SYM(31, eglQueryContext)
GLFWD_SYM(32, eglQueryString)
GLFWD_SYM(33, eglQuerySurface)
GLFWD_SYM(34, eglReleaseTexImage)
GLFWD_SYM(35, eglReleaseThread)
GLFWD_SYM(36, eglSurfaceAttrib)
GLFWD_SYM(37, eglSwapBuffers)
GLFWD_SYM(38, eglSwapInterval)
GLFWD_SYM(39, eglTerminate)
GLFWD_SYM(40, eglWaitClient)
GLFWD_SYM(41, eglWaitGL)
GLFWD_SYM(42, eglWaitNative)
GLFWD_SYM(43, eglWaitSync)
